let adminPin='',studentsCache=[],settingsCache=[];
const $=id=>document.getElementById(id);const show=(id,on)=>$(id)?.classList.toggle('hidden',!on);function adminMsg(t,type='info'){const e=$('adminMessage');if(e){e.textContent=t;e.className='message '+type;e.style.display='block';}}
function optionList(v){return String(v||'').split('|').filter(Boolean)}
async function adminLogin(){const pin=$('adminPin').value.trim();if(!pin)return adminMsg('Enter admin PIN.','error');try{const d=await apiCall('verifyAdmin',{pin});if(!d.valid)throw Error('Invalid Admin PIN.');adminPin=pin;show('loginCard',false);show('adminPanel',true);await refreshDashboard();adminMsg('Login successful.','success');}catch(e){adminMsg(e.message,'error');}}
function logout(){adminPin='';show('adminPanel',false);show('loginCard',true);}
async function refreshDashboard(){await Promise.all([loadStats(),loadStudents(),loadSettings()]);}
async function loadStats(){const d=await apiCall('stats',{pin:adminPin});['students','marks','deleted','fields'].forEach(k=>{if($('stat'+k[0].toUpperCase()+k.slice(1)))$('stat'+k[0].toUpperCase()+k.slice(1)).textContent=d[k]??0;});}
async function loadStudents(){const filters={Class:$('fClass')?.value||'',Section:$('fSection')?.value||'',Medium:$('fMedium')?.value||'',Trade:$('fTrade')?.value||'',"Job Role":$('fJob')?.value||'',Status:$('fStatus')?.value||'',search:$('studentSearch')?.value||''};studentsCache=await apiCall('students',{pin:adminPin,filters});renderStudentTable();}
function renderStudentTable(){const b=$('studentRows');if(!b)return;b.innerHTML=studentsCache.length?studentsCache.map((s,i)=>'<tr><td><input type="checkbox" class="student-check" data-row="'+s._row+'"></td><td>'+esc(s.Name)+'</td><td>'+esc(s.Class)+'</td><td>'+esc(s.Section)+'</td><td>'+esc(s.Roll)+'</td><td>'+esc(s.Medium)+'</td><td>'+esc(s.Trade)+'</td><td>'+esc(s['Job Role'])+'</td><td><button class="mini" onclick="editStudent('+s._row+')">Edit</button> <button class="mini danger" onclick="deleteStudent('+s._row+')">Delete</button></td></tr>').join(''):'<tr><td colspan="9">No students found.</td></tr>';$('studentCount').textContent=studentsCache.length+' visible records';}
function clearFilters(){['fClass','fSection','fMedium','fTrade','fJob','fStatus','studentSearch'].forEach(id=>{if($(id))$(id).value=''});loadStudents();}
function selectAll(){document.querySelectorAll('.student-check').forEach(x=>x.checked=true)}
function clearAll(){document.querySelectorAll('.student-check').forEach(x=>x.checked=false)}
function collectStudentFrom(s){const data={};settingsCache.forEach(f=>{if(f.enabled||f.system)data[f.field]=s[f.field]??''});return data;}
async function editStudent(row){const s=studentsCache.find(x=>Number(x._row)===Number(row));if(!s)return;const data=collectStudentFrom(s);const fields=settingsCache.filter(f=>f.enabled||f.system);for(const f of fields){if(f.field==='Status')continue;let v=prompt(f.field,data[f.field]||'');if(v===null)return;data[f.field]=v;}try{await apiCall('updateStudent',{pin:adminPin,row,data});adminMsg('Student updated.','success');await refreshDashboard();}catch(e){adminMsg(e.message,'error');}}
async function deleteStudent(row){const s=studentsCache.find(x=>Number(x._row)===Number(row));if(!s||!confirm('Delete '+s.Name+'?'))return;try{await apiCall('deleteStudent',{pin:adminPin,row});adminMsg('Student deleted.','success');await refreshDashboard();}catch(e){adminMsg(e.message,'error');}}
async function loadDeleted(){const d=await apiCall('deleted',{pin:adminPin});$('deletedRows').innerHTML=d.length?d.map(x=>'<tr><td>'+esc(x.deletedAt)+'</td><td>'+esc(x.type)+'</td><td><button class="mini" onclick="restoreRecord('+x.row+')">Restore</button></td></tr>').join(''):'<tr><td colspan="3">No deleted records.</td></tr>';}
async function restoreRecord(row){try{await apiCall('restore',{pin:adminPin,row});adminMsg('Record restored.','success');await loadDeleted();await refreshDashboard();}catch(e){adminMsg(e.message,'error');}}
async function saveMarks(){const data={Class:$('mClass').value,Roll:$('mRoll').value.trim(),Subject:$('mSubject').value.trim(),Theory:$('mTheory').value,Practical:$('mPractical').value,Max:$('mMax').value,Remarks:$('mRemarks').value};try{await apiCall('saveMarks',{pin:adminPin,data});adminMsg('Marks saved.','success');await loadStats();}catch(e){adminMsg(e.message,'error');}}
function fieldRow(f,i){return '<div class="builder-row" data-index="'+i+'"><input class="sf-name" value="'+esc(f.field)+'" '+(f.system?'readonly':'')+'><select class="sf-type"><option '+(f.type==='text'?'selected':'')+'>text</option><option '+(f.type==='dropdown'?'selected':'')+'>dropdown</option><option '+(f.type==='textarea'?'selected':'')+'>textarea</option><option '+(f.type==='tel'?'selected':'')+'>tel</option><option '+(f.type==='email'?'selected':'')+'>email</option><option '+(f.type==='number'?'selected':'')+'>number</option></select><input class="sf-options" placeholder="Options separated by |" value="'+esc(f.options)+'"><select class="sf-required"><option value="Yes" '+(f.required?'selected':'')+'>Required</option><option value="No" '+(!f.required?'selected':'')+'>Optional</option></select><input class="sf-classes" placeholder="All or 9th|10th" value="'+esc(f.onlyClasses)+'"><input class="sf-section" placeholder="Section" value="'+esc(f.section)+'"><label><input class="sf-enabled" type="checkbox" '+(f.enabled?'checked':'')+'> On</label><button class="mini danger" onclick="removeField('+i+')">Delete</button></div>';}
function renderBuilder(){const b=$('builder');b.innerHTML=settingsCache.map(fieldRow).join('');}
async function loadSettings(){settingsCache=await apiCall('settings');renderBuilder();}
function addField(){settingsCache.push({field:'New Field',type:'text',options:'',required:false,enabled:true,onlyClasses:'All',system:false,section:'Custom'});renderBuilder();}
function removeField(i){if(settingsCache[i].system){alert('System field cannot be removed. You can disable it only if it is not required.');return;}settingsCache.splice(i,1);renderBuilder();}
async function saveSettings(){const rows=[...document.querySelectorAll('.builder-row')];const next=rows.map((r,i)=>({...settingsCache[i],field:r.querySelector('.sf-name').value.trim(),type:r.querySelector('.sf-type').value,options:r.querySelector('.sf-options').value,required:r.querySelector('.sf-required').value==='Yes',onlyClasses:r.querySelector('.sf-classes').value||'All',section:r.querySelector('.sf-section').value||'Custom',enabled:r.querySelector('.sf-enabled').checked}));try{settingsCache=await apiCall('saveSettings',{pin:adminPin,settings:next});renderBuilder();adminMsg('Form Builder saved. Registration form will use the new fields immediately.','success');await loadStats();}catch(e){adminMsg(e.message,'error');}}
function showTab(tab){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('hidden',x.id!=='panel-'+tab));if(tab==='deleted')loadDeleted();if(tab==='settings')loadSettings();}
function saveApiUrl(){const v=$('apiUrl').value.trim();setApiUrl(v);adminMsg('API URL saved in this browser. For all visitors, also set it once in js/config.js.','success');}
async function setupInfo(){try{const d=await apiCall('setup');$('setupInfo').innerHTML='<b>Google Sheet:</b> <a target="_blank" href="'+d.sheetUrl+'">Open Sheet</a><br><small>Sheet ID: '+esc(d.sheetId)+'</small>'; }catch(e){$('setupInfo').textContent=e.message;}}
document.addEventListener('DOMContentLoaded',()=>{$('adminPin')?.addEventListener('keydown',e=>{if(e.key==='Enter')adminLogin()});$('apiUrl').value=localStorage.getItem('sandipani_api_url')||DEFAULT_API_URL||'';});
